FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN DATABASE_URL="postgresql://x:x@localhost:5432/x" npx prisma generate

EXPOSE 3000

CMD ["npx", "tsx", "src/index.ts"]